### ISSUE TITLE
failed to generate private der key file

### ISSUE THREAD

**Issue by jzimermann** [ulisesbocchio/spring-boot-security-saml-samples#5]
We are using the plugin and following the example that extends WebSecurityConfigurerAdapter using Okta. we got round to doing the setup on our Okta account and downloaded  the cert file that was provided. As specified by the configuration below we knew that we needed a private der file

``` 
.and()
.keyManager()
.privateKeyDERLocation("classpath:/okta.der")
.publicKeyPEMLocation("classpath:/okta.cert") 
```

We tried using open ssl to generate this file (This is the command we run):
```
openssl x509 -in okta.cert -outform der -out okta.der
```
This failed to work and was giving us the following exception:
```
Caused by: java.security.InvalidKeyException: IOException : DER input, Integer tag error
	at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:351) ~[na:1.8.0_65]
	at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:356) ~[na:1.8.0_65]
	at sun.security.rsa.RSAPrivateCrtKeyImpl.<init>(RSAPrivateCrtKeyImpl.java:91) ~[na:1.8.0_65]
	at sun.security.rsa.RSAPrivateCrtKeyImpl.newKey(RSAPrivateCrtKeyImpl.java:75) ~[na:1.8.0_65]
	at sun.security.rsa.RSAKeyFactory.generatePrivate(RSAKeyFactory.java:316) ~[na:1.8.0_65]
	at sun.security.rsa.RSAKeyFactory.engineGeneratePrivate(RSAKeyFactory.java:213) ~[na:1.8.0_65]
``` 

What we are wondering is wether those keys are a necessity and if so where we can get the pair generated since Okta does not seem to have provisions to generate a private der file

**Comment by ulisesbocchio** [comment]
@jzimermann did you get this resolve? Sorry for the massive delay
